### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ctcac00** [mongodb-developer/Google-Cloud-Semantic-Search#6]
Hi, this file [google-cloud-functions/embeddings/main.py](google-cloud-functions/embeddings/main.py) is missing in the repo

**Comment by voxic** [comment]
The file is here:
[https://github.com/mongodb-developer/Google-Cloud-Semantic-Search/blob/main/google-cloud-functions/generate-embeddings/main.py](https://github.com/mongodb-developer/Google-Cloud-Semantic-Search/blob/main/google-cloud-functions/generate-embeddings/main.py)
The links in the README.md was wrong.

**Comment by sis0k0** [comment]
resolved with #7 thanks @voxic
